controller_list:
  - name: /igus/joint_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints: 
       - j1
       - j2
       - j3
       - j4  
       - ee_joint

